application:
  name: job-spring-batch

spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

projeto:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/batch_projeto?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

batch:
  job:
    parameters:
      arquivoClientes: "file:src/main/resources/clientes.txt"

logging:
  file:
    name: ./logs/batch.log
  logback:
    rollingpolicy:
      max-history: 2
      max-file-size: 1MB